# -*- coding: utf-8 -*-
"""Task_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KaQYshC-xMeJqxoBkSMfgJsW5NcNQcTB
"""

# TASK 1

x = 8
print(x)