# -*- coding: utf-8 -*-
"""Task_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QT5RxJxNFZANAuol1PR6QuepVlpXjn-x
"""

# TASK 2

import numpy as np
import time

# Measure how long the creation takes
start = time.time()
array = np.random.rand(1000, 1000)
print(array)
creation_time = time.time() - start
print("Array creation time :", creation_time, "seconds")

# Convert the array into bytes
start = time.time()
array_bytes = array.tobytes()
print(array_bytes)

# Recreate the array from the bytes
start_time = time.time()
recreated_array = np.frombuffer(array_bytes, dtype=array.dtype).reshape(array.shape)
print(recreated_array)